<!DOCTYPE html>
<html lang="en">
  <head>
    <script>
      window.currentUser = null;
    </script>
    <script>
      window.rateUsdToNative = 1;
    </script>
    <title itemprop="name">Error handling, &quot;try...catch&quot;</title>
    <link href="pack/styles.93b05845f313a968119b.css" rel="stylesheet" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=yes, minimum-scale=1.0"
    />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <script>
      if (window.devicePixelRatio > 1)
        document.cookie =
          "pixelRatio=" +
          window.devicePixelRatio +
          ";path=/;expires=Tue, 19 Jan 2038 03:14:07 GMT";
    </script>
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:bold,italic,bolditalic"
      rel="stylesheet"
    />
    <link
      rel="apple-touch-icon-precomposed"

    <link rel="canonical" href="try-catch.html" />
    <meta name="msapplication-TileColor" content="#222A2C" />
    <meta name="msapplication-TileImage" content="/img/favicon/tileicon.png" />
    <link rel="icon" href="img/favicon/favicon.png" />
    <meta
      itemprop="image"
      content="https://javascript.info/img/site_preview_en_512x512.png"
    />
    <meta property="og:title" content='Error handling, "try...catch"' />
    <meta
      property="og:image"
      content="https://javascript.info/img/site_preview_en_1200x630.png"
    />
    <meta property="og:image:type" content="image/png" />

    <meta name="twitter:title" content='Error handling, "try...catch"' />
    <meta name="twitter:site" content="@iliakan" />
    <meta name="twitter:creator" content="@iliakan" />

    <link rel="prev" href="error-handling.html" />
    <link rel="next" href="custom-errors.html" />
    <script>
      window.GA_ID = "UA-2056213-15";
    </script>
    <script>
      window.YANDEX_METRIKA_ID = 32184394;
    </script>
    <script>
      (window.GoogleAnalyticsObject = "ga"),
        (window.ga = function () {
          window.ga.q.push(arguments);
        }),
        (window.ga.q = []),
        (window.ga.l = Date.now()),
        ga("create", GA_ID, "auto"),
        window.GTM_ID && ga("require", GTM_ID),
        window.currentUser
          ? ga("set", "&uid", currentUser.id)
          : ga("set", "anonymizeIp", !0),
        window.addEventListener("error", function (e) {
          var r = (e.filename || e.errorUrl) + ": " + (e.lineno || e.errorLine),
            n = e.stack || (e.error && e.error.stack);
          ga("send", "exception", {
            exDescription: e.message + " " + r + " " + n,
            exFatal: !0,
          });
        });
    </script>
    <script src="https://www.google-analytics.com/analytics.js" async></script>
    <script>
      ga("send", "pageview");
    </script>
    <script>
      (window.metrika = { reachGoal: function () {} }),
        (window.yandex_metrika_callbacks = [
          function () {
            try {
              (window.metrika = new Ya.Metrika({
                id: YANDEX_METRIKA_ID,
                webvisor: !0,
                clickmap: !0,
                params: { user: window.currentUser && window.currentUser.id },
              })),
                metrika.trackLinks({ delay: 150 }),
                window.addEventListener("error", function (r) {
                  window.metrika.reachGoal("JSERROR", {
                    src:
                      (r.filename || r.errorUrl) +
                      ": " +
                      (r.lineno || r.errorLine),
                    stack: r.stack || (r.error && r.error.stack),
                    message: r.message,
                  });
                });
            } catch (r) {}
          },
        ]);
    </script>
    <script src="https://mc.yandex.ru/metrika/watch.js" async></script>
    <script>
      window.RECAPTCHA_ID = "6LfmLAEVAAAAAJMykMnf7aY8nkyTRmYi2ynx51R1";
    </script>
    <script src="pack/init.810c8da2b4eed830d2da.js"></script>
    <script src="pack/head.282ce219a840c583fa6d.js" defer></script>
    <meta property="og:title" content='Error handling, "try...catch"' />
    <meta property="og:type" content="article" />
    <script src="pack/tutorial.dd771765a083d97231c4.js" defer></script>
    <script src="pack/footer.ce9ac5e9c03240648299.js" defer></script>
  </head>
  <body class="no-icons">

    <script>
          window.lang = "en";
        </script>
        <script>
          {
            let t = navigator.languages || [];
            t = t.map((t) => t.toLowerCase());
            let o,
              a,
              n = [];
            for (let o of window.langs)
              for (let a of t)
                if (a === o.code || a.startsWith(o.code + "-")) {
                  n.push(o);
                  break;
                }
            if ("en" === lang) {
              let t = n.find((t) => "en" != t.code);
              t &&
                "ru" != t.code &&
                ((o = `\n            According to your browser language headers, you know ${t.name}. Please help to <a href="https://github.com/javascript-tutorial/${t.code}.javascript.info#readme">translate the tutorial</a> into your language!\n            Thank you!\n          `),
                (a = "notify-translate-tutorial"));
            } else if ("ru" != lang) {
              n.find((t) => "en" == t.code) &&
                ((o = `\n            According to your browser headers, you know English. Please help to <a href="https://github.com/javascript-tutorial/${lang}.javascript.info#readme">translate the tutorial</a>.\n            Thank you!\n          `),
                (a = "notify-translate-tutorial-local"));
            }
            if (o) {
              let t = `<div class="notification notification_top notification_info sitetoolbar__notification" style="display:none" id="${a}">\n          <div class="notification__content">${o}</div>\n          <button class="notification__close" title="Close"></button>\n        </div>`;
              document.write(t), showTopNotification();
            }
          }
        </script>
        <div class="sitetoolbar__content">
          <div class="sitetoolbar__lang-switcher">
            <button class="sitetoolbar__dropdown-button" data-dropdown-toggler>
              EN
            </button>
            <div class="sitetoolbar__dropdown-wrap">
              <div class="sitetoolbar__dropdown-body">
                <div class="sitetoolbar__lang-switcher-body">
                  <div class="supported-langs supported-langs_toolbar">
                    <div class="supported-langs__container">
                      <ul class="supported-langs__list" style="height: 200px">
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://ar.javascript.info/try-catch"
                            ><span class="supported-langs__brief">AR</span
                            ><span >عربي</span></a
                          >
                        </li>
                        <li
                          class="
                            supported-langs__item supported-langs__item_current
                          "
                        >
                          <a class="supported-langs__link" href="try-catch.html"
                            ><span class="supported-langs__brief">EN</span
                            ><span 
                              >English</span
                            ></a
                          >
                        </li>
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://es.javascript.info/try-catch"
                            ><span class="supported-langs__brief">ES</span
                            ><span 
                              >Español</span
                            ></a
                          >
                        </li>
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://fr.javascript.info/try-catch"
                            ><span class="supported-langs__brief">FR</span
                            ><span 
                              >Français</span
                            ></a
                          >
                        </li>
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://it.javascript.info/try-catch"
                            ><span class="supported-langs__brief">IT</span
                            ><span 
                              >Italiano</span
                            ></a
                          >
                        </li>
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://ja.javascript.info/try-catch"
                            ><span class="supported-langs__brief">JA</span
                            ><span 
                              >日本語</span
                            ></a
                          >
                        </li>
                      </ul>
                      <ul class="supported-langs__list" style="height: 128px">
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://ko.javascript.info/try-catch"
                            ><span class="supported-langs__brief">KO</span
                            ><span 
                              >한국어</span
                            ></a
                          >
                        </li>
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href=try-catch"
                            ><span class="supported-langs__brief">RU</span
                            ><span 
                              >Русский</span
                            ></a
                          >
                        </li>
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://tr.javascript.info/try-catch"
                            ><span class="supported-langs__brief">TR</span
                            ><span 
                              >Türkçe</span
                            ></a
                          >
                        </li>
                        <li class="supported-langs__item">
                          <a
                            class="supported-langs__link"
                            href="https://zh.javascript.info/try-catch"
                            ><span class="supported-langs__brief">ZH</span
                            ><span 
                              >简体中文</span
                            ></a
                          >
                        </li>
                      </ul>
                    </div>
                    <div class="supported-langs__text">
                      <p>
                        We want to make this open-source project available for
                        people all around the world.
                      </p>
                      <p>
                        <a href="translate.html">Help to translate</a> the
                        content of this tutorial to your language!
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="sitetoolbar__logo-wrap">
            <a
              class="sitetoolbar__link sitetoolbar__link_logo"
              href="index.html"
              ><img
                class="sitetoolbar__logo sitetoolbar__logo_normal"
                src="img/sitetoolbar__logo_en.svg"
                width="200"
                alt=""
                role="presentation"
              /><img
                class="sitetoolbar__logo sitetoolbar__logo_small"
                src="img/sitetoolbar__logo_small_en.svg"
                width="70"
                alt=""
                role="presentation"
              />
              <script>
                Array.prototype.forEach.call(
                  document.querySelectorAll("img.sitetoolbar__logo"),
                  function (e) {
                    let t = document.createElement("object");
                    (t.type = "image/svg+xml"),
                      (t.className = e.className),
                      (t.style.cssText = "left:0;top:0;position:absolute"),
                      (t.onload = function () {
                        (t.onload = null), (e.style.visibility = "hidden");
                      }),
                      (t.data = e.src),
                      e.parentNode.insertBefore(t, e);
                  }
                );
              </script></a
            >


              <form
                class="sitetoolbar__search"
                method="GET"
                action="https://javascript.info/search"
              >
                <button
                  class="sitetoolbar__search-toggle"
                  type="button"
                ></button>
                <div class="sitetoolbar__search-input">
                  <div class="text-input">
                    <input
                      class="text-input__control"
                      name="query"
                      placeholder="Search on Javascript.info"
                      required="required"
                      type="text"
                    />
                  </div>
                  <button class="sitetoolbar__find" type="submit">
                    Search
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="tablet-menu">
          <div class="tablet-menu__line">
            <div class="tablet-menu__content">
              <form
                class="tablet-menu-search"
                action="https://javascript.info/search/"
              >
                <input
                  class="tablet-menu-search__input"
                  type="search"
                  name="query"
                  placeholder="Search in the tutorial"
                  required="required"
                /><button
                  class="tablet-menu-search__button"
                  type="submit"
                  name="type"
                  value="articles"
                >
                  Search
                </button>
              </form>
            </div>
          </div>
          <div class="tablet-menu__line">
            <div class="tablet-menu__content">
              <div class="share-icons">
                <span class="share-icons__title">Share</span
                >2Ftry-catch"
                  rel="nofollow"
                ></a
                >2Ftry-catch"
                  rel="nofollow"
                ></a>
              </div>
            </div>
          </div>
          <div class="tablet-menu__line">
            <div class="tablet-menu__content">
              <select
                class="
                  tablet-menu__nav
                  input-select input-select input-select_small
                "
                onchange="if(this.value) window.location.href=this.value"
              >
                <option value="https://ar.javascript.info/try-catch">
                  عربي
                </option>
                <option value="https://javascript.info/try-catch" selected>
                  English
                </option>
                <option value="https://es.javascript.info/try-catch">
                  Español
                </option>
                <option value="https://fr.javascript.info/try-catch">
                  Français
                </option>
                <option value="https://it.javascript.info/try-catch">
                  Italiano
                </option>
                <option value="https://ja.javascript.info/try-catch">
                  日本語
                </option>
                <option value="https://ko.javascript.info/try-catch">
                  한국어
                </option>
                <option value=try-catch">
                  Русский
                </option>
                <option value="https://tr.javascript.info/try-catch">
                  Türkçe
                </option>
                <option value="https://zh.javascript.info/try-catch">
                  简体中文
                </option>
              </select>
            </div>
          </div>
        </div>
        <progress
          class="tutorial-progress"
          data-sticky
          value="73"
          max="92"
          data-tooltip="Lesson 73 of 92"
        ></progress>
      </div>
      <div class="page page_sidebar_on page_inner_padding">
        <script>
          if (localStorage.noSidebar) {
            document.querySelector(".page").classList.remove("page_sidebar_on");
            let e = document.querySelector(".page-wrapper");
            e && e.classList.remove("page-wrapper_sidebar_on");
          }
          setTimeout(function () {
            document
              .querySelector(".page")
              .classList.add("page_sidebar-animation-on");
          });
        </script>
        <div class="page__inner">
          <main class="main main_width-limit">
            <header class="main__header">
              <div class="main__header-inner">
                <div class="main__header-group">
                  <ol class="breadcrumbs">
                    <li class="breadcrumbs__item breadcrumbs__item_home">
                      <a class="breadcrumbs__link" href="index.html"
                        ><span class="breadcrumbs__hidden-text"
                          >Tutorial</span
                        ></a
                      >
                    </li>
                    <li class="breadcrumbs__item" id="breadcrumb-1">
                      <a class="breadcrumbs__link" href="js.html"
                        ><span>The JavaScript language</span></a
                      >
                    </li>
                    <li class="breadcrumbs__item" id="breadcrumb-2">
                      <a class="breadcrumbs__link" href="error-handling.html"
                        ><span>Error handling</span></a
                      >
                    </li>
                    <script type="application/ld+json">
                      {
                        "@context": "https://schema.org",
                        "@type": "BreadcrumbList",
                        "itemListElement": [
                          {
                            "@type": "ListItem",
                            "position": 1,
                            "name": "Tutorial",
                            "item": "https://javascript.info/"
                          },
                          {
                            "@type": "ListItem",
                            "position": 2,
                            "name": "The JavaScript language",
                            "item": "https://javascript.info/js"
                          },
                          {
                            "@type": "ListItem",
                            "position": 3,
                            "name": "Error handling",
                            "item": "https://javascript.info/error-handling"
                          }
                        ]
                      }
                    </script>
                  </ol>
                  <div
                    class="updated-at"
                    data-tooltip="Last updated at 25th January 2021"
                  >
                    <div class="updated-at__content">25th January 2021</div>
                  </div>
                </div>
                <h1 class="main__header-title">
                  Error handling, &quot;try...catch&quot;
                </h1>
              </div>
            </header>
            <div class="content">
              <article
                class="formatted"
                itemscope
                itemtype="http://schema.org/TechArticle"
              >
                <meta itemprop="name" content='Error handling, "try...catch"' />
                <div
                  itemprop="author"
                  itemscope
                  itemtype="http://schema.org/Person"
                >
                  <meta itemprop="email" content="iliakan@gmail.com" /><meta
                    itemprop="name"
                    content="Ilya Kantor"
                  />
                </div>
                <div itemprop="articleBody">
                  <p>
                    No matter how great we are at programming, sometimes our
                    scripts have errors. They may occur because of our mistakes,
                    an unexpected user input, an erroneous server response, and
                    for a thousand other reasons.
                  </p>
                  <p>
                    Usually, a script “dies” (immediately stops) in case of an
                    error, printing it to console.
                  </p>
                  <p>
                    But there’s a syntax construct <code>try...catch</code> that
                    allows us to “catch” errors so the script can, instead of
                    dying, do something more reasonable.
                  </p>
                  <h2>
                    <a
                      class="main__anchor"
                      name="the-try-catch-syntax"
                      href="try-catch.html#the-try-catch-syntax"
                      >The “try…catch” syntax</a
                    >
                  </h2>
                  <p>
                    The <code>try...catch</code> construct has two main blocks:
                    <code>try</code>, and then <code>catch</code>:
                  </p>
                  <div id="gzu31knvf9" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {

  // code...

} catch (err) {

  // error handling

}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>It works like this:</p>
                  <ol>
                    <li>
                      First, the code in <code>try {...}</code> is executed.
                    </li>
                    <li>
                      If there were no errors, then <code>catch (err)</code> is
                      ignored: the execution reaches the end of
                      <code>try</code> and goes on, skipping <code>catch</code>.
                    </li>
                    <li>
                      If an error occurs, then the <code>try</code> execution is
                      stopped, and control flows to the beginning of
                      <code>catch (err)</code>. The <code>err</code> variable
                      (we can use any name for it) will contain an error object
                      with details about what happened.
                    </li>
                  </ol>
                  <figure>
                    <div class="image" style="width: 514px">
                      <div
                        class="image__ratio"
                        style="padding-top: 79.96108949416343%"
                      ></div>
                      <object
                        type="image/svg+xml"
                        data="article/try-catch/try-catch-flow.svg"
                        width="514"
                        height="411"
                        class="image__image"
                      >
                        <img
                          src="article/try-catch/try-catch-flow.svg"
                          alt=""
                          width="514"
                          height="411"
                        />
                      </object>
                    </div>
                  </figure>
                  <p>
                    So, an error inside the <code>try {...}</code> block does
                    not kill the script – we have a chance to handle it in
                    <code>catch</code>.
                  </p>
                  <p>Let’s look at some examples.</p>
                  <ul>
                    <li>
                      <p>
                        An errorless example: shows <code>alert</code>
                        <code>(1)</code> and <code>(2)</code>:
                      </p>
                      <div
                        id="5ylv6cbtv7"
                        data-trusted="1"
                        class="code-example"
                        data-highlight='[{"start":6,"cols":[{"start":33,"end":40}]},{"start":2,"cols":[{"start":34,"end":41}]}]'
                      >
                        <div class="codebox code-example__codebox">
                          <div class="toolbar codebox__toolbar">
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="run"
                                data-action="run"
                                class="toolbar__button toolbar__button_run"
                              ></a>
                            </div>
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="open in sandbox"
                                target="_blank"
                                data-action="edit"
                                class="toolbar__button toolbar__button_edit"
                              ></a>
                            </div>
                          </div>
                          <div class="codebox__code" data-code="1">
                            <pre
                              class="line-numbers language-javascript"
                            ><code>try {

  alert('Start of try runs');  // (1) &lt;--

  // ...no errors here

  alert('End of try runs');   // (2) &lt;--

} catch (err) {

  alert('Catch is ignored, because there are no errors'); // (3)

}</code></pre>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li>
                      <p>
                        An example with an error: shows <code>(1)</code> and
                        <code>(3)</code>:
                      </p>
                      <div
                        id="j25pcdmw7w"
                        data-trusted="1"
                        class="code-example"
                        data-highlight='[{"start":10,"cols":[{"start":35,"end":42}]},{"start":4,"end":4},{"start":2,"cols":[{"start":34,"end":41}]}]'
                      >
                        <div class="codebox code-example__codebox">
                          <div class="toolbar codebox__toolbar">
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="run"
                                data-action="run"
                                class="toolbar__button toolbar__button_run"
                              ></a>
                            </div>
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="open in sandbox"
                                target="_blank"
                                data-action="edit"
                                class="toolbar__button toolbar__button_edit"
                              ></a>
                            </div>
                          </div>
                          <div class="codebox__code" data-code="1">
                            <pre
                              class="line-numbers language-javascript"
                            ><code>try {

  alert('Start of try runs');  // (1) &lt;--

  lalala; // error, variable is not defined!

  alert('End of try (never reached)');  // (2)

} catch (err) {

  alert(`Error has occurred!`); // (3) &lt;--

}</code></pre>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                  <div class="important important_warn">
                    <div class="important__header">
                      <span class="important__type"
                        ><code>try...catch</code> only works for runtime
                        errors</span
                      >
                    </div>
                    <div class="important__content">
                      <p>
                        For <code>try...catch</code> to work, the code must be
                        runnable. In other words, it should be valid JavaScript.
                      </p>
                      <p>
                        It won’t work if the code is syntactically wrong, for
                        instance it has unmatched curly braces:
                      </p>
                      <div
                        id="kpub9mnx58"
                        data-trusted="1"
                        class="code-example"
                      >
                        <div class="codebox code-example__codebox">
                          <div class="toolbar codebox__toolbar">
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="run"
                                data-action="run"
                                class="toolbar__button toolbar__button_run"
                              ></a>
                            </div>
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="open in sandbox"
                                target="_blank"
                                data-action="edit"
                                class="toolbar__button toolbar__button_edit"
                              ></a>
                            </div>
                          </div>
                          <div class="codebox__code" data-code="1">
                            <pre
                              class="line-numbers language-javascript"
                            ><code>try {
  {{{{{{{{{{{{
} catch (err) {
  alert(&quot;The engine can't understand this code, it's invalid&quot;);
}</code></pre>
                          </div>
                        </div>
                      </div>
                      <p>
                        The JavaScript engine first reads the code, and then
                        runs it. The errors that occur on the reading phase are
                        called “parse-time” errors and are unrecoverable (from
                        inside that code). That’s because the engine can’t
                        understand the code.
                      </p>
                      <p>
                        So, <code>try...catch</code> can only handle errors that
                        occur in valid code. Such errors are called “runtime
                        errors” or, sometimes, “exceptions”.
                      </p>
                    </div>
                  </div>
                  <div class="important important_warn">
                    <div class="important__header">
                      <span class="important__type"
                        ><code>try...catch</code> works synchronously</span
                      >
                    </div>
                    <div class="important__content">
                      <p>
                        If an exception happens in “scheduled” code, like in
                        <code>setTimeout</code>, then
                        <code>try...catch</code> won’t catch it:
                      </p>
                      <div
                        id="vh4jhbqpu8"
                        data-trusted="1"
                        class="code-example"
                      >
                        <div class="codebox code-example__codebox">
                          <div class="toolbar codebox__toolbar">
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="run"
                                data-action="run"
                                class="toolbar__button toolbar__button_run"
                              ></a>
                            </div>
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="open in sandbox"
                                target="_blank"
                                data-action="edit"
                                class="toolbar__button toolbar__button_edit"
                              ></a>
                            </div>
                          </div>
                          <div class="codebox__code" data-code="1">
                            <pre
                              class="line-numbers language-javascript"
                            ><code>try {
  setTimeout(function() {
    noSuchVariable; // script will die here
  }, 1000);
} catch (err) {
  alert( &quot;won't work&quot; );
}</code></pre>
                          </div>
                        </div>
                      </div>
                      <p>
                        That’s because the function itself is executed later,
                        when the engine has already left the
                        <code>try...catch</code> construct.
                      </p>
                      <p>
                        To catch an exception inside a scheduled function,
                        <code>try...catch</code> must be inside that function:
                      </p>
                      <div
                        id="1tsumtwjsq"
                        data-trusted="1"
                        class="code-example"
                      >
                        <div class="codebox code-example__codebox">
                          <div class="toolbar codebox__toolbar">
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="run"
                                data-action="run"
                                class="toolbar__button toolbar__button_run"
                              ></a>
                            </div>
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="open in sandbox"
                                target="_blank"
                                data-action="edit"
                                class="toolbar__button toolbar__button_edit"
                              ></a>
                            </div>
                          </div>
                          <div class="codebox__code" data-code="1">
                            <pre
                              class="line-numbers language-javascript"
                            ><code>setTimeout(function() {
  try {
    noSuchVariable; // try...catch handles the error!
  } catch {
    alert( &quot;error is caught here!&quot; );
  }
}, 1000);</code></pre>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <h2>
                    <a
                      class="main__anchor"
                      name="error-object"
                      href="try-catch.html#error-object"
                      >Error object</a
                    >
                  </h2>
                  <p>
                    When an error occurs, JavaScript generates an object
                    containing the details about it. The object is then passed
                    as an argument to <code>catch</code>:
                  </p>
                  <div id="ekhm7a045f" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
  // ...
} catch (err) { // &lt;-- the &quot;error object&quot;, could use another word instead of err
  // ...
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    For all built-in errors, the error object has two main
                    properties:
                  </p>
                  <dl>
                    <dt><code>name</code></dt>
                    <dd>
                      Error name. For instance, for an undefined variable that’s
                      <code>&quot;ReferenceError&quot;</code>.
                    </dd>
                    <dt><code>message</code></dt>
                    <dd>Textual message about error details.</dd>
                  </dl>
                  <p>
                    There are other non-standard properties available in most
                    environments. One of most widely used and supported is:
                  </p>
                  <dl>
                    <dt><code>stack</code></dt>
                    <dd>
                      Current call stack: a string with information about the
                      sequence of nested calls that led to the error. Used for
                      debugging purposes.
                    </dd>
                  </dl>
                  <p>For instance:</p>
                  <div
                    id="ce4l5nxrhr"
                    data-trusted="0"
                    class="code-example"
                    data-highlight='[{"start":1,"end":1}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
  lalala; // error, variable is not defined!
} catch (err) {
  alert(err.name); // ReferenceError
  alert(err.message); // lalala is not defined
  alert(err.stack); // ReferenceError: lalala is not defined at (...call stack)

  // Can also show an error as a whole
  // The error is converted to string as &quot;name: message&quot;
  alert(err); // ReferenceError: lalala is not defined
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <h2>
                    <a
                      class="main__anchor"
                      name="optional-catch-binding"
                      href="try-catch.html#optional-catch-binding"
                      >Optional “catch” binding</a
                    >
                  </h2>
                  <div class="important important_warn">
                    <div class="important__header">
                      <span class="important__type">A recent addition</span>
                    </div>
                    <div class="important__content">
                      This is a recent addition to the language. Old browsers
                      may need polyfills.
                    </div>
                  </div>
                  <p>
                    If we don’t need error details, <code>catch</code> may omit
                    it:
                  </p>
                  <div id="hyczur8k5x" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
  // ...
} catch { // &lt;-- without (err)
  // ...
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <h2>
                    <a
                      class="main__anchor"
                      name="using-try-catch"
                      href="try-catch.html#using-try-catch"
                      >Using “try…catch”</a
                    >
                  </h2>
                  <p>
                    Let’s explore a real-life use case of
                    <code>try...catch</code>.
                  </p>
                  <p>
                    As we already know, JavaScript supports the
                    <a
                      href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse"
                      >JSON.parse(str)</a
                    >
                    method to read JSON-encoded values.
                  </p>
                  <p>
                    Usually it’s used to decode data received over the network,
                    from the server or another source.
                  </p>
                  <p>
                    We receive it and call <code>JSON.parse</code> like this:
                  </p>
                  <div
                    id="dvgvqpix7a"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":2,"end":2}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let json = '{&quot;name&quot;:&quot;John&quot;, &quot;age&quot;: 30}'; // data from the server

let user = JSON.parse(json); // convert the text representation to JS object

// now user is an object with properties from the string
alert( user.name ); // John
alert( user.age );  // 30</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    You can find more detailed information about JSON in the
                    <a href="json.html">JSON methods, toJSON</a> chapter.
                  </p>
                  <p>
                    <strong
                      >If <code>json</code> is malformed,
                      <code>JSON.parse</code> generates an error, so the script
                      “dies”.</strong
                    >
                  </p>
                  <p>Should we be satisfied with that? Of course not!</p>
                  <p>
                    This way, if something’s wrong with the data, the visitor
                    will never know that (unless they open the developer
                    console). And people really don’t like when something “just
                    dies” without any error message.
                  </p>
                  <p>Let’s use <code>try...catch</code> to handle the error:</p>
                  <div
                    id="8hho65a9na"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":8,"end":11},{"start":4,"end":4}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let json = &quot;{ bad json }&quot;;

try {

  let user = JSON.parse(json); // &lt;-- when an error occurs...
  alert( user.name ); // doesn't work

} catch (err) {
  // ...the execution jumps here
  alert( &quot;Our apologies, the data has errors, we'll try to request it one more time.&quot; );
  alert( err.name );
  alert( err.message );
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    Here we use the <code>catch</code> block only to show the
                    message, but we can do much more: send a new network
                    request, suggest an alternative to the visitor, send
                    information about the error to a logging facility, … . All
                    much better than just dying.
                  </p>
                  <h2>
                    <a
                      class="main__anchor"
                      name="throwing-our-own-errors"
                      href="try-catch.html#throwing-our-own-errors"
                      >Throwing our own errors</a
                    >
                  </h2>
                  <p>
                    What if <code>json</code> is syntactically correct, but
                    doesn’t have a required <code>name</code> property?
                  </p>
                  <p>Like this:</p>
                  <div
                    id="clqi8tgeqk"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":5,"end":5}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let json = '{ &quot;age&quot;: 30 }'; // incomplete data

try {

  let user = JSON.parse(json); // &lt;-- no errors
  alert( user.name ); // no name!

} catch (err) {
  alert( &quot;doesn't execute&quot; );
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    Here <code>JSON.parse</code> runs normally, but the absence
                    of <code>name</code> is actually an error for us.
                  </p>
                  <p>
                    To unify error handling, we’ll use the
                    <code>throw</code> operator.
                  </p>
                  <h3>
                    <a
                      class="main__anchor"
                      name="throw-operator"
                      href="try-catch.html#throw-operator"
                      >“Throw” operator</a
                    >
                  </h3>
                  <p>The <code>throw</code> operator generates an error.</p>
                  <p>The syntax is:</p>
                  <div id="ofsss9e8jq" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>throw &lt;error object&gt;</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    Technically, we can use anything as an error object. That
                    may be even a primitive, like a number or a string, but it’s
                    better to use objects, preferably with <code>name</code> and
                    <code>message</code> properties (to stay somewhat compatible
                    with built-in errors).
                  </p>
                  <p>
                    JavaScript has many built-in constructors for standard
                    errors: <code>Error</code>, <code>SyntaxError</code>,
                    <code>ReferenceError</code>, <code>TypeError</code> and
                    others. We can use them to create error objects as well.
                  </p>
                  <p>Their syntax is:</p>
                  <div id="dsasdf5m50" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let error = new Error(message);
// or
let error = new SyntaxError(message);
let error = new ReferenceError(message);
// ...</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    For built-in errors (not for any objects, just for errors),
                    the <code>name</code> property is exactly the name of the
                    constructor. And <code>message</code> is taken from the
                    argument.
                  </p>
                  <p>For instance:</p>
                  <div id="em0s15mn9y" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let error = new Error(&quot;Things happen o_O&quot;);

alert(error.name); // Error
alert(error.message); // Things happen o_O</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    Let’s see what kind of error
                    <code>JSON.parse</code> generates:
                  </p>
                  <div
                    id="q7p6s5slps"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":3,"end":3}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
  JSON.parse(&quot;{ bad json o_O }&quot;);
} catch (err) {
  alert(err.name); // SyntaxError
  alert(err.message); // Unexpected token b in JSON at position 2
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>As we can see, that’s a <code>SyntaxError</code>.</p>
                  <p>
                    And in our case, the absence of <code>name</code> is an
                    error, as users must have a <code>name</code>.
                  </p>
                  <p>So let’s throw it:</p>
                  <div
                    id="3p2bnrrjr7"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":7,"end":7}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let json = '{ &quot;age&quot;: 30 }'; // incomplete data

try {

  let user = JSON.parse(json); // &lt;-- no errors

  if (!user.name) {
    throw new SyntaxError(&quot;Incomplete data: no name&quot;); // (*)
  }

  alert( user.name );

} catch (err) {
  alert( &quot;JSON Error: &quot; + err.message ); // JSON Error: Incomplete data: no name
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    In the line <code>(*)</code>, the
                    <code>throw</code> operator generates a
                    <code>SyntaxError</code> with the given
                    <code>message</code>, the same way as JavaScript would
                    generate it itself. The execution of
                    <code>try</code> immediately stops and the control flow
                    jumps into <code>catch</code>.
                  </p>
                  <p>
                    Now <code>catch</code> became a single place for all error
                    handling: both for <code>JSON.parse</code> and other cases.
                  </p>
                  <h2>
                    <a
                      class="main__anchor"
                      name="rethrowing"
                      href="try-catch.html#rethrowing"
                      >Rethrowing</a
                    >
                  </h2>
                  <p>
                    In the example above we use <code>try...catch</code> to
                    handle incorrect data. But is it possible that
                    <em>another unexpected error</em> occurs within the
                    <code>try {...}</code> block? Like a programming error
                    (variable is not defined) or something else, not just this
                    “incorrect data” thing.
                  </p>
                  <p>For example:</p>
                  <div id="zjg1h2o6s7" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let json = '{ &quot;age&quot;: 30 }'; // incomplete data

try {
  user = JSON.parse(json); // &lt;-- forgot to put &quot;let&quot; before user

  // ...
} catch (err) {
  alert(&quot;JSON Error: &quot; + err); // JSON Error: ReferenceError: user is not defined
  // (no JSON Error actually)
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    Of course, everything’s possible! Programmers do make
                    mistakes. Even in open-source utilities used by millions for
                    decades – suddenly a bug may be discovered that leads to
                    terrible hacks.
                  </p>
                  <p>
                    In our case, <code>try...catch</code> is placed to catch
                    “incorrect data” errors. But by its nature,
                    <code>catch</code> gets <em>all</em> errors from
                    <code>try</code>. Here it gets an unexpected error, but
                    still shows the same
                    <code>&quot;JSON Error&quot;</code> message. That’s wrong
                    and also makes the code more difficult to debug.
                  </p>
                  <p>
                    To avoid such problems, we can employ the “rethrowing”
                    technique. The rule is simple:
                  </p>
                  <p>
                    <strong
                      >Catch should only process errors that it knows and
                      “rethrow” all others.</strong
                    >
                  </p>
                  <p>
                    The “rethrowing” technique can be explained in more detail
                    as:
                  </p>
                  <ol>
                    <li>Catch gets all errors.</li>
                    <li>
                      In the <code>catch (err) {...}</code> block we analyze the
                      error object <code>err</code>.
                    </li>
                    <li>
                      If we don’t know how to handle it, we do
                      <code>throw err</code>.
                    </li>
                  </ol>
                  <p>
                    Usually, we can check the error type using the
                    <code>instanceof</code> operator:
                  </p>
                  <div
                    id="abgfwma2qt"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":3,"end":3}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
  user = { /*...*/ };
} catch (err) {
  if (err instanceof ReferenceError) {
    alert('ReferenceError'); // &quot;ReferenceError&quot; for accessing an undefined variable
  }
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    We can also get the error class name from
                    <code>err.name</code> property. All native errors have it.
                    Another option is to read <code>err.constructor.name</code>.
                  </p>
                  <p>
                    In the code below, we use rethrowing so that
                    <code>catch</code> only handles <code>SyntaxError</code>:
                  </p>
                  <div
                    id="skbwu806e3"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":15,"end":19},{"start":9,"end":9}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let json = '{ &quot;age&quot;: 30 }'; // incomplete data
try {

  let user = JSON.parse(json);

  if (!user.name) {
    throw new SyntaxError(&quot;Incomplete data: no name&quot;);
  }

  blabla(); // unexpected error

  alert( user.name );

} catch (err) {

  if (err instanceof SyntaxError) {
    alert( &quot;JSON Error: &quot; + err.message );
  } else {
    throw err; // rethrow (*)
  }

}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    The error throwing on line <code>(*)</code> from inside
                    <code>catch</code> block “falls out” of
                    <code>try...catch</code> and can be either caught by an
                    outer <code>try...catch</code> construct (if it exists), or
                    it kills the script.
                  </p>
                  <p>
                    So the <code>catch</code> block actually handles only errors
                    that it knows how to deal with and “skips” all others.
                  </p>
                  <p>
                    The example below demonstrates how such errors can be caught
                    by one more level of <code>try...catch</code>:
                  </p>
                  <div
                    id="rff5sj9wk"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":17,"end":17},{"start":9,"end":9},{"start":5,"end":5}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>function readData() {
  let json = '{ &quot;age&quot;: 30 }';

  try {
    // ...
    blabla(); // error!
  } catch (err) {
    // ...
    if (!(err instanceof SyntaxError)) {
      throw err; // rethrow (don't know how to deal with it)
    }
  }
}

try {
  readData();
} catch (err) {
  alert( &quot;External catch got: &quot; + err ); // caught it!
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    Here <code>readData</code> only knows how to handle
                    <code>SyntaxError</code>, while the outer
                    <code>try...catch</code> knows how to handle everything.
                  </p>
                  <h2>
                    <a
                      class="main__anchor"
                      name="try-catch-finally"
                      href="try-catch.html#try-catch-finally"
                      >try…catch…finally</a
                    >
                  </h2>
                  <p>Wait, that’s not all.</p>
                  <p>
                    The <code>try...catch</code> construct may have one more
                    code clause: <code>finally</code>.
                  </p>
                  <p>If it exists, it runs in all cases:</p>
                  <ul>
                    <li>after <code>try</code>, if there were no errors,</li>
                    <li>after <code>catch</code>, if there were errors.</li>
                  </ul>
                  <p>The extended syntax looks like this:</p>
                  <div
                    id="j459e80ffe"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":4,"cols":[{"start":2,"end":9}]},{"start":2,"cols":[{"start":2,"end":7}]},{"start":0,"cols":[{"start":0,"end":3}]}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
   ... try to execute the code ...
} catch (err) {
   ... handle errors ...
} finally {
   ... execute always ...
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>Try running this code:</p>
                  <div id="f5yka5u29d" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
  alert( 'try' );
  if (confirm('Make an error?')) BAD_CODE();
} catch (err) {
  alert( 'catch' );
} finally {
  alert( 'finally' );
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>The code has two ways of execution:</p>
                  <ol>
                    <li>
                      If you answer “Yes” to “Make an error?”, then
                      <code>try -&gt; catch -&gt; finally</code>.
                    </li>
                    <li>
                      If you say “No”, then <code>try -&gt; finally</code>.
                    </li>
                  </ol>
                  <p>
                    The <code>finally</code> clause is often used when we start
                    doing something and want to finalize it in any case of
                    outcome.
                  </p>
                  <p>
                    For instance, we want to measure the time that a Fibonacci
                    numbers function <code>fib(n)</code> takes. Naturally, we
                    can start measuring before it runs and finish afterwards.
                    But what if there’s an error during the function call? In
                    particular, the implementation of <code>fib(n)</code> in the
                    code below returns an error for negative or non-integer
                    numbers.
                  </p>
                  <p>
                    The <code>finally</code> clause is a great place to finish
                    the measurements no matter what.
                  </p>
                  <p>
                    Here <code>finally</code> guarantees that the time will be
                    measured correctly in both situations – in case of a
                    successful execution of <code>fib</code> and in case of an
                    error in it:
                  </p>
                  <div
                    id="rtq22wusfv"
                    data-trusted="1"
                    class="code-example"
                    data-highlight='[{"start":17,"end":19}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="run"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>let num = +prompt(&quot;Enter a positive integer number?&quot;, 35)

let diff, result;

function fib(n) {
  if (n &lt; 0 || Math.trunc(n) != n) {
    throw new Error(&quot;Must not be negative, and also an integer.&quot;);
  }
  return n &lt;= 1 ? n : fib(n - 1) + fib(n - 2);
}

let start = Date.now();

try {
  result = fib(num);
} catch (err) {
  result = 0;
} finally {
  diff = Date.now() - start;
}

alert(result || &quot;error occurred&quot;);

alert( `execution took ${diff}ms` );</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    You can check by running the code with entering
                    <code>35</code> into <code>prompt</code> – it executes
                    normally, <code>finally</code> after <code>try</code>. And
                    then enter <code>-1</code> – there will be an immediate
                    error, and the execution will take <code>0ms</code>. Both
                    measurements are done correctly.
                  </p>
                  <p>
                    In other words, the function may finish with
                    <code>return</code> or <code>throw</code>, that doesn’t
                    matter. The <code>finally</code> clause executes in both
                    cases.
                  </p>
                  <div class="important important_smart">
                    <div class="important__header">
                      <span class="important__type"
                        >Variables are local inside
                        <code>try...catch...finally</code></span
                      >
                    </div>
                    <div class="important__content">
                      <p>
                        Please note that <code>result</code> and
                        <code>diff</code> variables in the code above are
                        declared <em>before</em> <code>try...catch</code>.
                      </p>
                      <p>
                        Otherwise, if we declared <code>let</code> in
                        <code>try</code> block, it would only be visible inside
                        of it.
                      </p>
                    </div>
                  </div>
                  <div class="important important_smart">
                    <div class="important__header">
                      <span class="important__type"
                        ><code>finally</code> and <code>return</code></span
                      >
                    </div>
                    <div class="important__content">
                      <p>
                        The <code>finally</code> clause works for
                        <em>any</em> exit from <code>try...catch</code>. That
                        includes an explicit <code>return</code>.
                      </p>
                      <p>
                        In the example below, there’s a <code>return</code> in
                        <code>try</code>. In this case, <code>finally</code> is
                        executed just before the control returns to the outer
                        code.
                      </p>
                      <div
                        id="q5yk3shkch"
                        data-trusted="1"
                        class="code-example"
                        data-highlight='[{"start":8,"end":8},{"start":3,"end":3}]'
                      >
                        <div class="codebox code-example__codebox">
                          <div class="toolbar codebox__toolbar">
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="run"
                                data-action="run"
                                class="toolbar__button toolbar__button_run"
                              ></a>
                            </div>
                            <div class="toolbar__tool">
                              <a
                                href="try-catch.html#"
                                title="open in sandbox"
                                target="_blank"
                                data-action="edit"
                                class="toolbar__button toolbar__button_edit"
                              ></a>
                            </div>
                          </div>
                          <div class="codebox__code" data-code="1">
                            <pre
                              class="line-numbers language-javascript"
                            ><code>function func() {

  try {
    return 1;

  } catch (err) {
    /* ... */
  } finally {
    alert( 'finally' );
  }
}

alert( func() ); // first works alert from finally, and then this one</code></pre>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="important important_smart">
                    <div class="important__header">
                      <span class="important__type"
                        ><code>try...finally</code></span
                      >
                    </div>
                    <div class="important__content">
                      <p>
                        The <code>try...finally</code> construct, without
                        <code>catch</code> clause, is also useful. We apply it
                        when we don’t want to handle errors here (let them fall
                        through), but want to be sure that processes that we
                        started are finalized.
                      </p>
                      <div
                        id="yeqr7qstip"
                        data-trusted="1"
                        class="code-example"
                      >
                        <div class="codebox code-example__codebox">
                          <div class="codebox__code" data-code="1">
                            <pre
                              class="line-numbers language-javascript"
                            ><code>function func() {
  // start doing something that needs completion (like measurements)
  try {
    // ...
  } finally {
    // complete that thing even if all dies
  }
}</code></pre>
                          </div>
                        </div>
                      </div>
                      <p>
                        In the code above, an error inside
                        <code>try</code> always falls out, because there’s no
                        <code>catch</code>. But <code>finally</code> works
                        before the execution flow leaves the function.
                      </p>
                    </div>
                  </div>
                  <h2>
                    <a
                      class="main__anchor"
                      name="global-catch"
                      href="try-catch.html#global-catch"
                      >Global catch</a
                    >
                  </h2>
                  <div class="important important_warn">
                    <div class="important__header">
                      <span class="important__type">Environment-specific</span>
                    </div>
                    <div class="important__content">
                      <p>
                        The information from this section is not a part of the
                        core JavaScript.
                      </p>
                    </div>
                  </div>
                  <p>
                    Let’s imagine we’ve got a fatal error outside of
                    <code>try...catch</code>, and the script died. Like a
                    programming error or some other terrible thing.
                  </p>
                  <p>
                    Is there a way to react on such occurrences? We may want to
                    log the error, show something to the user (normally they
                    don’t see error messages), etc.
                  </p>
                  <p>
                    There is none in the specification, but environments usually
                    provide it, because it’s really useful. For instance,
                    Node.js has
                    <a
                      href="https://nodejs.org/api/process.html#process_event_uncaughtexception"
                      ><code>process.on(&quot;uncaughtException&quot;)</code></a
                    >
                    for that. And in the browser we can assign a function to the
                    special
                    <a
                      href="https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror"
                      >window.onerror</a
                    >
                    property, that will run in case of an uncaught error.
                  </p>
                  <p>The syntax:</p>
                  <div id="l95c7isfqm" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>window.onerror = function(message, url, line, col, error) {
  // ...
};</code></pre>
                      </div>
                    </div>
                  </div>
                  <dl>
                    <dt><code>message</code></dt>
                    <dd>Error message.</dd>
                    <dt><code>url</code></dt>
                    <dd>URL of the script where error happened.</dd>
                    <dt><code>line</code>, <code>col</code></dt>
                    <dd>Line and column numbers where error happened.</dd>
                    <dt><code>error</code></dt>
                    <dd>Error object.</dd>
                  </dl>
                  <p>For instance:</p>
                  <div
                    id="b06mjrvum3"
                    data-trusted="0"
                    class="code-example"
                    data-demo-height="1"
                    data-refresh="1"
                    data-highlight='[{"start":1,"end":3}]'
                  >
                    <div class="codebox code-example__codebox">
                      <div class="toolbar codebox__toolbar">
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="show"
                            data-action="run"
                            class="toolbar__button toolbar__button_run"
                          ></a>
                        </div>
                        <div class="toolbar__tool">
                          <a
                            href="try-catch.html#"
                            title="open in sandbox"
                            target="_blank"
                            data-action="edit"
                            class="toolbar__button toolbar__button_edit"
                          ></a>
                        </div>
                      </div>
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-markup"
                        ><code>&lt;script&gt;
  window.onerror = function(message, url, line, col, error) {
    alert(`${message}\n At ${line}:${col} of ${url}`);
  };

  function readData() {
    badFunc(); // Whoops, something went wrong!
  }

  readData();
&lt;/script&gt;</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    The role of the global handler
                    <code>window.onerror</code> is usually not to recover the
                    script execution – that’s probably impossible in case of
                    programming errors, but to send the error message to
                    developers.
                  </p>
                  <p>
                    There are also web-services that provide error-logging for
                    such cases, like
                    <a href="https://errorception.com"
                      >https://errorception.com</a
                    >
                    or
                    <a href="http://www.muscula.com">http://www.muscula.com</a>.
                  </p>
                  <p>They work like this:</p>
                  <ol>
                    <li>
                      We register at the service and get a piece of JS (or a
                      script URL) from them to insert on pages.
                    </li>
                    <li>
                      That JS script sets a custom
                      <code>window.onerror</code> function.
                    </li>
                    <li>
                      When an error occurs, it sends a network request about it
                      to the service.
                    </li>
                    <li>
                      We can log in to the service web interface and see errors.
                    </li>
                  </ol>
                  <h2>
                    <a
                      class="main__anchor"
                      name="summary"
                      href="try-catch.html#summary"
                      >Summary</a
                    >
                  </h2>
                  <p>
                    The <code>try...catch</code> construct allows to handle
                    runtime errors. It literally allows to “try” running the
                    code and “catch” errors that may occur in it.
                  </p>
                  <p>The syntax is:</p>
                  <div id="sn6dxuwn1b" data-trusted="1" class="code-example">
                    <div class="codebox code-example__codebox">
                      <div class="codebox__code" data-code="1">
                        <pre
                          class="line-numbers language-javascript"
                        ><code>try {
  // run this code
} catch (err) {
  // if an error happened, then jump here
  // err is the error object
} finally {
  // do in any case after try/catch
}</code></pre>
                      </div>
                    </div>
                  </div>
                  <p>
                    There may be no <code>catch</code> section or no
                    <code>finally</code>, so shorter constructs
                    <code>try...catch</code> and <code>try...finally</code> are
                    also valid.
                  </p>
                  <p>Error objects have following properties:</p>
                  <ul>
                    <li>
                      <code>message</code> – the human-readable error message.
                    </li>
                    <li>
                      <code>name</code> – the string with error name (error
                      constructor name).
                    </li>
                    <li>
                      <code>stack</code> (non-standard, but well-supported) –
                      the stack at the moment of error creation.
                    </li>
                  </ul>
                  <p>
                    If an error object is not needed, we can omit it by using
                    <code>catch {</code> instead of <code>catch (err) {</code>.
                  </p>
                  <p>
                    We can also generate our own errors using the
                    <code>throw</code> operator. Technically, the argument of
                    <code>throw</code> can be anything, but usually it’s an
                    error object inheriting from the built-in
                    <code>Error</code> class. More on extending errors in the
                    next chapter.
                  </p>
                  <p>
                    <em>Rethrowing</em> is a very important pattern of error
                    handling: a <code>catch</code> block usually expects and
                    knows how to handle the particular error type, so it should
                    rethrow errors it doesn’t know.
                  </p>
                  <p>
                    Even if we don’t have <code>try...catch</code>, most
                    environments allow us to setup a “global” error handler to
                    catch errors that “fall out”. In-browser, that’s
                    <code>window.onerror</code>.
                  </p>
                </div>
              </article>
              <div class="tasks formatted">
                <h2 class="tasks__title" id="tasks">
                  <a
                    class="
                      tasks__title-anchor
                      main__anchor main__anchor main__anchor_noicon
                    "
                    href="try-catch.html#tasks"
                    >Tasks</a
                  >
                </h2>
                <div class="task tasks__task">
                  <div class="task__header">
                    <div class="task__title-wrap">
                      <h3 class="task__title">
                        <a
                          class="main__anchor"
                          href="try-catch.html#finally-or-just-the-code"
                          name="finally-or-just-the-code"
                          >Finally or just the code?</a
                        >
                      </h3>
                      <a
                        class="task__open-link"
                        href="task/finally-or-code-after.html"
                        target="_blank"
                      ></a>
                    </div>
                    <div class="task__header-note">
                      <span
                        class="task__importance"
                        title="How important is the task, from 1 to 5"
                        >importance: 5</span
                      >
                    </div>
                    <div class="task__content">
                      <div class="task__formatted">
                        <p>Compare the two code fragments.</p>
                        <ol>
                          <li>
                            <p>
                              The first one uses <code>finally</code> to execute
                              the code after <code>try...catch</code>:
                            </p>
                            <div
                              id="au0fe9eov0"
                              data-trusted="1"
                              class="code-example"
                              data-highlight='[{"start":5,"end":5}]'
                            >
                              <div class="codebox code-example__codebox">
                                <div class="codebox__code" data-code="1">
                                  <pre
                                    class="line-numbers language-javascript"
                                  ><code>try {
  work work
} catch (err) {
  handle errors
} finally {
  cleanup the working space
}</code></pre>
                                </div>
                              </div>
                            </div>
                          </li>
                          <li>
                            <p>
                              The second fragment puts the cleaning right after
                              <code>try...catch</code>:
                            </p>
                            <div
                              id="2o61abqik1"
                              data-trusted="1"
                              class="code-example"
                              data-highlight='[{"start":6,"end":6}]'
                            >
                              <div class="codebox code-example__codebox">
                                <div class="codebox__code" data-code="1">
                                  <pre
                                    class="line-numbers language-javascript"
                                  ><code>try {
  work work
} catch (err) {
  handle errors
}

cleanup the working space</code></pre>
                                </div>
                              </div>
                            </div>
                          </li>
                        </ol>
                        <p>
                          We definitely need the cleanup after the work, doesn’t
                          matter if there was an error or not.
                        </p>
                        <p>
                          Is there an advantage here in using
                          <code>finally</code> or both code fragments are equal?
                          If there is such an advantage, then give an example
                          when it matters.
                        </p>
                      </div>
                      <button class="task__solution" type="button">
                        solution
                      </button>
                      <div class="task__answer">
                        <div class="task__answer-content">
                          <div class="formatted">
                            <p>
                              The difference becomes obvious when we look at the
                              code inside a function.
                            </p>
                            <p>
                              The behavior is different if there’s a “jump out”
                              of <code>try...catch</code>.
                            </p>
                            <p>
                              For instance, when there’s a
                              <code>return</code> inside
                              <code>try...catch</code>. The
                              <code>finally</code> clause works in case of
                              <em>any</em> exit from <code>try...catch</code>,
                              even via the <code>return</code> statement: right
                              after <code>try...catch</code> is done, but before
                              the calling code gets the control.
                            </p>
                            <div
                              id="ho9l2pl75v"
                              data-trusted="1"
                              class="code-example"
                              data-highlight='[{"start":3,"end":3}]'
                            >
                              <div class="codebox code-example__codebox">
                                <div class="toolbar codebox__toolbar">
                                  <div class="toolbar__tool">
                                    <a
                                      href="try-catch.html#"
                                      title="run"
                                      data-action="run"
                                      class="
                                        toolbar__button toolbar__button_run
                                      "
                                    ></a>
                                  </div>
                                  <div class="toolbar__tool">
                                    <a
                                      href="try-catch.html#"
                                      title="open in sandbox"
                                      target="_blank"
                                      data-action="edit"
                                      class="
                                        toolbar__button toolbar__button_edit
                                      "
                                    ></a>
                                  </div>
                                </div>
                                <div class="codebox__code" data-code="1">
                                  <pre
                                    class="line-numbers language-javascript"
                                  ><code>function f() {
  try {
    alert('start');
    return &quot;result&quot;;
  } catch (err) {
    /// ...
  } finally {
    alert('cleanup!');
  }
}

f(); // cleanup!</code></pre>
                                </div>
                              </div>
                            </div>
                            <p>
                              …Or when there’s a <code>throw</code>, like here:
                            </p>
                            <div
                              id="9di1rrjkir"
                              data-trusted="1"
                              class="code-example"
                              data-highlight='[{"start":7,"end":7}]'
                            >
                              <div class="codebox code-example__codebox">
                                <div class="toolbar codebox__toolbar">
                                  <div class="toolbar__tool">
                                    <a
                                      href="try-catch.html#"
                                      title="run"
                                      data-action="run"
                                      class="
                                        toolbar__button toolbar__button_run
                                      "
                                    ></a>
                                  </div>
                                  <div class="toolbar__tool">
                                    <a
                                      href="try-catch.html#"
                                      title="open in sandbox"
                                      target="_blank"
                                      data-action="edit"
                                      class="
                                        toolbar__button toolbar__button_edit
                                      "
                                    ></a>
                                  </div>
                                </div>
                                <div class="codebox__code" data-code="1">
                                  <pre
                                    class="line-numbers language-javascript"
                                  ><code>function f() {
  try {
    alert('start');
    throw new Error(&quot;an error&quot;);
  } catch (err) {
    // ...
    if(&quot;can't handle the error&quot;) {
      throw err;
    }

  } finally {
    alert('cleanup!')
  }
}

f(); // cleanup!</code></pre>
                                </div>
                              </div>
                            </div>
                            <p>
                              It’s <code>finally</code> that guarantees the
                              cleanup here. If we just put the code at the end
                              of <code>f</code>, it wouldn’t run in these
                              situations.
                            </p>
                          </div>
                        </div>
                        <button
                          class="close-button task__answer-close"
                          type="button"
                          title="close"
                        ></button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="page__nav-wrap">
              <a
                class="page__nav page__nav_prev"
                href="error-handling.html"
                data-tooltip="Error handling"
                ><span class="page__nav-text"
                  ><span class="page__nav-text-shortcut"></span></span
                ><span class="page__nav-text-alternate"
                  >Previous lesson</span
                ></a
              ><a
                class="page__nav page__nav_next"
                href="custom-errors.html"
                data-tooltip="Custom errors, extending Error"
                ><span class="page__nav-text"
                  ><span class="page__nav-text-shortcut"></span></span
                ><span class="page__nav-text-alternate">Next lesson</span></a
              >
            </div>
            <div class="article-tablet-foot tablet-only">
              <div class="article-tablet-foot__layout">
                <div class="share-icons">
                  <span class="share-icons__title">Share</span
                  ><a
                    class="share share_tw"
                    href="https://twitter.com/share?url=https%3A%2F%2Fjavascript.info%2Ftry-catch"
                    rel="nofollow"
                  ></a
                  ><a
                    class="share share_fb"
                    href="https://www.facebook.com/sharer/sharer.php?s=100&amp;p%5Burl%5D=https%3A%2F%2Fjavascript.info%2Ftry-catch"
                    rel="nofollow"
                  ></a>
                </div>
                <div class="article-tablet-foot__map">
                  <a
                    class="map"
                    href="tutorial/map.html"
                    data-action="tutorial-map"
                    ><span class="map__text">Tutorial map</span></a
                  >
                </div>
              </div>
            </div>
            
                  <a href="try-catch.html#comments" name="comments">Comments</a>
                </h2>
                <div class="comments__read-before">
                  <span class="comments__read-before-link"
                    >read this before commenting…</span
                  >
                  <div class="comments__read-before-popup">
                    <div class="comments__read-before-popup-i">
                      <ul>
                        <li>
                          If you have suggestions what to improve - please
                          <a
                            href="https://github.com/javascript-tutorial/en.javascript.info/issues/new"
                            >submit a GitHub issue</a
                          >
                          or a pull request instead of commenting.
                        </li>
                        <li>
                          If you can't understand something in the article –
                          please elaborate.
                        </li>
                        <li>
                          To insert few words of code, use the
                          <code>&lt;code&gt;</code> tag, for several lines –
                          wrap them in <code>&lt;pre&gt;</code> tag, for more
                          than 10 lines – use a sandbox (<a
                            href="https://plnkr.co/edit/?p=preview"
                            >plnkr</a
                          >, <a href="https://jsbin.com">jsbin</a>,
                          <a href="http://codepen.io">codepen</a>…)
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div id="disqus_thread"></div>
              <script>
                var disqus_config = function () {
                  if (!this.page) this.page = {};
                  Object.assign(this.page, {
                    url: "https:\/\/javascript.info\/try-catch",
                    identifier: "\/try-catch",
                  });
                };
              </script>
              <script>
                var disqus_shortname = "javascriptinfo";
              </script>
              <script>
                var disqus_enabled = true;
              </script>
            </div>
          </main>
        </div>

                <nav class="sidebar__navigation">
                  <ul class="sidebar__navigation-links">
                    <li class="sidebar__navigation-link">
                      <a class="sidebar__link" href="error-handling.html"
                        >Error handling</a
                      >
                    </li>
                  </ul>
                </nav>
                <h4 class="sidebar__section-title">Lesson navigation</h4>
                <nav class="sidebar__navigation">
                  <ul class="sidebar__navigation-links">
                    <li class="sidebar__navigation-link">
                   try-catch.html#the-try-catch-syntax"
                        >The “try…catch” syntax</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                   try-catch.html#error-object"
                        >Error object</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                   try-catch.html#optional-catch-binding"
                        >Optional “catch” binding</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                   try-catch.html#using-try-catch"
                        >Using “try…catch”</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                   try-catch.html#throwing-our-own-errors"
                        >Throwing our own errors</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                      <a class="sidebar__link" href="try-catch.html#rethrowing"
                        >Rethrowing</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                   try-catch.html#try-catch-finally"
                        >try…catch…finally</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                   try-catch.html#global-catch"
                        >Global catch</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                      <a class="sidebar__link" href="try-catch.html
                  </ul>
                </nav>
                <nav class="sidebar__navigation">
                  <ul class="sidebar__navigation-links">
                    <li class="sidebar__navigation-link">
                      <a class="sidebar__link" href="try-catch.html#tasks"
                        >Tasks (1)</a
                      >
                    </li>
                    <li class="sidebar__navigation-link">
                      <a class="sidebar__link" href="try-catch.html#comments"
                        >Comments</a
                      >
                    </li>
                  </ul>
                </nav>
              </div>
           <a
                  class="share share_tw sidebar__share"
                  href="https://twitter.com/share?url=https%3A%2F%2Fjavascript.info%2Ftry-catch"
                  rel="nofollow"
                ></a
                ><a
                  class="share share_fb sidebar__share"
                  href="https://www.facebook.com/sharer/sharer.php?s=100&amp;p[url]=https%3A%2F%2Fjavascript.info%2Ftry-catch"
                  rel="nofollow"
                ></a>
                <a
                  class="sidebar__link"
                  href="https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/10-error-handling/1-try-catch"
                  rel="nofollow"
                  >Edit on GitHub</a
                >
              </div>
              <div class="sidebar__section" id="sponsorBar">
                <div class="sidebar__section-title" id="sponsorBarTitle"></div>
                <div id="sponsorBarContent"></div>
                <script>
                  window.initSponsorBar();
                </script>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="page-footer">
      <ul class="page-footer__list">
        <li class="page-footer__item page-footer__item_copy">
          ©&nbsp;2007—2021&nbsp; Ilya Kantor
        </li>
        <li class="page-footer__item page-footer__item_about">
          <a class="page-footer__link" href="about.html">about the project</a>
        </li>
        <li class="page-footer__item page-footer__item_contact">
          <a class="page-footer__link" href="about.html#contact-us"
            >contact us</a
          >
        </li>
        <li class="page-footer__item page-footer__item_terms">
          <a class="page-footer__link" href="terms.html">terms of usage</a>
        </li>
        <li class="page-footer__item page-footer__item_privacy">
          <a class="page-footer__link" href="privacy.html">privacy policy</a>
        </li>
      </ul>
    </div>
  </body>
</html>
